sonar.projectKey=Berthin-01_SmartridePropre
sonar.organization=berthin-01
sonar.projectName=SmartridePropre
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.language=js
sonar.sourceEncoding=UTF-8